### ISSUE TITLE
GOME harvester stuck collecting unavailable datasets

### ISSUE THREAD

**Issue by georgiana-b** [NextGeoss/ckanext-nextgeossharvest#115] opened 2019-12-19 15:59 UTC
After extensively testing the GOME harvester I've noticed the following pattern:

From `2019-06-01` until `2019-07-31` it is collecting 10 datasets from each collection except `SO2` and `SO2mass` which are returning the message that they are unavailable at the source:

You can see in the image below that the other collections (`NO2` and `TropNO2` were collected):
![image](https://user-images.githubusercontent.com/8862002/69817979-13cf3980-11fc-11ea-934e-2b44c005e67b.png)

From `2019-07-31` all the datasets appear as unavailable regardless of their collection. You can see in the pic below that the last available datasets from `NO2` and `TtropNO2` are on `2019-07-30`. From `2019-07-31` onwards they fail as well.

![image](https://user-images.githubusercontent.com/8862002/69818510-2eee7900-11fd-11ea-82df-279a08a5a988.png)

These unavailable datasets don't appear as errors though. They are just ignored and the harvester appears as running but collecting 0.

Running the harvester again only reiterates those last 10 datasets from `2019-07-31` until `2019-08-08` over and over even though they keep appearing as unavailable. 

![image](https://user-images.githubusercontent.com/8862002/69819626-9e656800-11ff-11ea-89e8-2e38b7a9a971.png)

From what I understand from the logs above, there are no datasets at the source beyond `2019-08-08`. If that's the case, why don't we just exit the harvester immediately so that it doesn't waste time on  those unavailable datasets over and over. 

LE:
The source contains much more recent datasets. So there are 2 problems here:
- that some of the ones before `2019-08-08` appear as unavailable
- that those after `2019-08-08` are ignored

**Comment by georgiana-b** [comment] 2019-12-19 16:04
Could we also make sure that those datasets are really missing from the source? 
And if they really are,  would be good if you could ask the people at GOME about this. Maybe they can investigate why those datasets are unavailable.

**Comment by joaandrade** [comment] 2019-12-19 16:11
Hi @georgiana-b, you can check the available datasets at [https://wdc.dlr.de/data_products/VIEWER/](https://wdc.dlr.de/data_products/VIEWER/)

![image](https://user-images.githubusercontent.com/8322111/71189093-2b896300-227a-11ea-8b0e-a9b54a7e14b8.png)

Hope this helps.
João

**Comment by joaandrade** [comment] 2019-12-19 16:12
In any case, @davidcordeiro-deimos can try to run the harvester locally in January.

**Comment by georgiana-b** [comment] 2019-12-19 16:27
Yes, I tried it locally as well but we get the same issue on production.

**Comment by georgiana-b** [comment] 2019-12-19 16:30
Thank you for sharing the link @joaandrade. In that case the problem is much broader because at the source the latest data is for `2019-12-12` whereas the harvester is stuck at `2019-08-08`.

![image](https://user-images.githubusercontent.com/8862002/71190558-182fc500-2285-11ea-8e6e-b80e31a755be.png)

**Comment by georgiana-b** [comment] 2019-12-19 16:34
I updated the title and the description accordingly.

**Comment by joaandrade** [comment] 2019-12-19 16:45
@davidcordeiro-deimos can you take a look on this after the vacations?

**Comment by davidcordeiro-deimos** [comment] 2020-01-06 11:43
@georgiana-b In order to have the same setup, could you provide the harvester configuration that you used locally?

**Comment by georgiana-b** [comment] 2020-01-06 12:14
This one:

```json
{
   "start_date": "2019-06-01",
    "make_private": false
}
```

**Comment by davidcordeiro-deimos** [comment] 2020-01-06 16:18
@georgiana-b Currently the harvester is only able to look 10 days after the last product collected. However, throughout the 5 collections, there are no products between 31/07/2019 and 10/08/2019 (11 days), thus the harvester got stuck and it is not able to find more recent products.

As per the suggestion of @joaandrade, the solution that will be implemented is to make this time interval configurable through the harvest configuration. I contacted the data provider to see what is the maximum expected product drought.

The pull request will be made as soon as possible.

**Comment by georgiana-b** [comment] 2020-01-07 08:45
@davidcordeiro-deimos Nice. That solves the problem of unavailable datasets and clarifies why there are none after the 08-08-2019. 

The only issue I see left is this:

> Running the harvester again only reiterates those last 10 datasets from 2019-07-31 until 2019-08-08 over and over even though they keep appearing as unavailable.

Why is the harvester going back? I found it a bit odd. Normally it should either collect the next datasets or stop if there is nothing new to collect. Don't you think?

**Comment by davidcordeiro-deimos** [comment] 2020-01-07 09:51
@georgiana-b That is expected behavior for continuous running harvesters due to the fact that for almost all of them the restart date of the following jobs is the date of the last product harvested.

Since it is assumed that this data provider is to supply data continuously (until further notice there will be new products), the harvester is also supposed to be kept running in order to always catch the new products.
 
Thus, due to the issue described in the previous comment and the harvester nature, it was continuously stuck in those 11 days without data.

I hope this clarifies your questions, otherwise, let me know.

**Comment by georgiana-b** [comment] 2020-01-07 14:15
Well if it starts from the last date it should try to search for the *next* 10 days, not for for the *past* 10 days.
That's what normally happens, right? It should look for datasets from `2019-08-08` onwards, see there are none and stop.

The fact that is keeps harvesting those past 10 ones is a bug. If your argument is that the harvester is trying to gather them again because they were unavailable the first time, then it should be doing that for all the unavailable ones, not just the last 10. 
The `SO2` and `SO2mass` collections appear as unavailable even in `2019-07-13` but the harvester is moving past them anyway. 

We need a consistent way to handle unavailable datasets.

**Comment by davidcordeiro-deimos** [comment] 2020-01-07 16:04
It seems I did not make myself clear, indeed the harvester looks at the next 10 days after the restart date.

> The SO2 and SO2mass collections appear as unavailable even in 2019-07-13 but the harvester is moving past them anyway.

It is assumed that the products of all collections are ingested at similar timeframes, thus if we find a collection product at a more recent date than a date without a certain collection, it is assumed that collection product for that older date will not exist. 

And in fact, for those collections, it seems that there is no data since 2018.

**Comment by georgiana-b** [comment] 2020-01-08 11:04
Ok, so we can agree to move past the datasets that are not available. There is no reason in trying to fetch them again and again since they are not there.

Could you please make sure that the harvester moves on to the next restart date? 

I just tested again the GOME harvester after the changes in https://github.com/NextGeoss/ckanext-nextgeossharvest/pull/121 and I encountered the same issue.

I started with this configuration:

```json
{
   "start_date": "2019-07-01",
   "time_interval": 15,
    "make_private": false
}
```
On the first run the harvester tried to collect the datasets from  `2019-07-01` until `2019-07-15`. 
On the second run, instead of moving on to collect from `2019-07-15` until `2019-07-30` it tried again to collect the same files from `2019-07-01` until `2019-07-15`. 

Do you see this behaviour too?

**Comment by davidcordeiro-deimos** [comment] 2020-01-08 11:39
The only knowledge that each job has from prior jobs is the date of the last product harvested.

However, this specific harvester does not have any update mechanism, thus if a product has already been collected, it will be skipped and the date will not be stored on the current job.

So the issue that you are having is due to the fact that you are setting up a start date on which another harvester already has collected all the products.

So my suggestion is to set up a configuration as:

```
{
   "start_date": "2019-08-01",
   "time_interval": 15,
    "make_private": false
}
```
and the harvester should be able to exhibit a proper behavior.

**Comment by georgiana-b** [comment] 2020-01-08 12:17
I understand.  But even if a dataset is skipped for various reasons (that the dataset already exists, that the dataset is not available at the source, etc), that day was taken into consideration so the harvester should move to the next day. 

Don't you agree it makes more sense to store the date of the skipped ones? 
This way, the harvester would run normally and keep skipping until it reaches datasets that haven't been harvested before or the end of the queue.

**Comment by joaandrade** [comment] 2020-01-08 12:48
Hi @georgiana-b,
We understand that this harvester should follow a different approach to prevent failures on long periods without datasets or already existent datasets. However, for now, we should avoid to spend more effort in this effort since we have the workaround, presented by David in the previous comments, and it allows to restart the harvester in prioduction. In any case, we will take in consideration a future release of this harvester.

**Comment by georgiana-b** [comment] 2020-01-08 16:11
Fair enough. The behaviour from `2019-08-01` further is normal and the source seems to be quite unstable so it might not be worth the extra effort.

I will approve the pull request mentioning the workaround. 

Thank you for giving proper consideration.

**Comment by JGulic** [comment] 2020-01-16 09:56
The PR has been merged.

This issue will be closed with the following note:
**_Since the decision is not to spend more time on fixing this harvester, we are going to merge the PR and close the issue, and we should all have in mind that this issue may appear in the future again._**

**Closed by JGulic** 2020-01-16 09:56 UTC
